import {useMemo,useState} from 'react';
import {Btn} from './ui';

const f='w-full border border-cream-300 rounded-lg px-3 py-2 bg-white';
export default function NewOrder({stock,customers,productStock={},settings,menu={},canOverride=false,close,add,next}){
  const groups=['Lunch menu','Daily nasta'];
  const [category,setCategory]=useState(groups[0]),[c,setC]=useState(customers[0]?.id??''),[lines,setLines]=useState([{item:Object.keys(menu)[0],qty:1}]),[service,setService]=useState('Delivery'),[note,setNote]=useState(''),[discount,setDiscount]=useState('0'),[cash,setCash]=useState(''),[qr,setQr]=useState(''),[digitalMethod,setDigitalMethod]=useState('eSewa'),[digital,setDigital]=useState(''),[warn,setWarn]=useState(false),[error,setError]=useState('');
  const products=Object.entries(menu).filter(([,v])=>(v.category||'Lunch menu')===category);
  const subtotal=lines.reduce((n,l)=>n+(menu[l.item]?.price||0)*(+l.qty||0),0),discountAmount=+discount||0,taxable=Math.max(0,subtotal-discountAmount),vat=settings?.vatEnabled?Math.round(taxable*(+settings.vatRate||13)*100)/100:0,total=taxable+vat,paid=(+cash||0)+(+qr||0)+(+digital||0);
  const allocation=useMemo(()=>{const available={...productStock},finishedUses={};const need={};lines.forEach(l=>{const prepared=Math.min(+l.qty||0,Math.max(0,available[l.item]||0));available[l.item]=(available[l.item]||0)-prepared;finishedUses[l.item]=(finishedUses[l.item]||0)+prepared;const toPrepare=(+l.qty||0)-prepared;Object.entries(menu[l.item]?.r||{}).forEach(([k,v])=>need[k]=(need[k]||0)+v*toPrepare)});return {need,finishedUses}},[lines,productStock,menu]);
  const {need,finishedUses}=allocation;
  const emptyNotice=<div className="fixed inset-0 bg-black/40 grid place-items-center p-3 sm:p-4 z-10"><div role="dialog" aria-modal="true" className="bg-cream-50 rounded-2xl p-5 w-full max-w-md text-center grid gap-3"><h2 className="font-bold text-lg">{Object.keys(menu).length?'No customers yet':'No menu items yet'}</h2><p className="text-sm text-stone-600">{Object.keys(menu).length?'Add a customer from the Customers page before creating a bill.':'Add your items and prices under Business settings → Order categories and menu before creating a bill.'}</p><Btn type="button" onClick={close}>Close</Btn></div></div>;
  if(!customers.length||!Object.keys(menu).length)return emptyNotice;
  const short=stock.filter(s=>(need[s.name]||0)>s.qty).map(s=>s.name);
  const addLine=()=>setLines([...lines,{item:products[0]?.[0]||Object.keys(menu)[0],qty:1}]);
  const go=()=>{if(!Number.isInteger(+c)||!customers.some(x=>x.id===+c))return setError('Select a customer first. Add one from the Customers page if the list is empty.');if(!lines.length||lines.some(l=>!Number.isInteger(+l.qty)||+l.qty<1))return setError('Each item must have a whole number quantity of at least 1.');if(discountAmount<0||discountAmount>subtotal)return setError('Discount must be between zero and the subtotal.');if([cash,qr,digital].some(x=>x!==''&&(!Number.isFinite(+x)||+x<0))||paid>total)return setError('Payment amounts must be zero or more and cannot exceed the invoice total.');if(short.length&&!warn){if(!canOverride)return setError(`Not enough stock: ${short.join(', ')}. Ask an administrator to approve this order.`);return setWarn(true)}add({id:next,c:+c,category,lines:lines.map(l=>({...l,qty:+l.qty,price:menu[l.item].price})),item:lines[0].item,qty:lines.reduce((n,l)=>n+l.qty,0),finishedUses,service,note:note.trim(),status:short.length?'Pending':'Preparing',payments:[...(cash>0?[{method:'Cash',amount:+cash}]:[]),...(qr>0?[{method:'QR',amount:+qr}]:[]),...(digital>0?[{method:digitalMethod,amount:+digital}]:[])],driver:null,createdAt:new Date().toISOString(),subtotal,discount:discountAmount,vat,vatRate:+settings?.vatRate||13,amount:total},need)};
  return <div className="fixed inset-0 bg-black/40 grid place-items-center p-3 sm:p-4 z-10"><div role="dialog" aria-modal="true" aria-labelledby="new-order-title" className="bg-cream-50 rounded-2xl p-4 sm:p-5 w-full max-w-xl max-h-[92dvh] overflow-y-auto overscroll-contain"><h2 id="new-order-title" className="font-bold text-lg mb-3">New customer bill</h2><div className="grid gap-3 text-sm">
   <label>Category first<select className={f} value={category} onChange={e=>{const v=e.target.value;setCategory(v);setLines([{item:Object.entries(menu).find(([,p])=>(p.category||'Lunch menu')===v)?.[0]||Object.keys(menu)[0],qty:1}])}}>{groups.map(x=><option key={x}>{x}</option>)}</select></label>
   <div className="rounded-lg bg-cream-100 p-3"><b>{category}</b><div className="grid sm:grid-cols-3 gap-2 mt-2">{products.map(([name,p])=><button type="button" key={name} onClick={()=>setLines([...lines,{item:name,qty:1}])} className="text-left rounded-lg bg-white border border-cream-300 p-2"><span className="font-semibold">{name}</span><small className="block">Rs. {p.price}</small></button>)}</div></div>
   <label>Customer<select className={f} value={c} onChange={e=>setC(e.target.value)}>{customers.map(x=><option key={x.id} value={x.id}>{x.name} · {x.phone}</option>)}</select></label>
   <div className="grid sm:grid-cols-2 gap-3"><label>Order type<select className={f} value={service} onChange={e=>setService(e.target.value)}><option>Delivery</option><option>Pickup</option><option>Dine-in</option></select></label><label>Kitchen / delivery note<input className={f} maxLength="180" placeholder="Allergies, no chilli, delivery instructions…" value={note} onChange={e=>setNote(e.target.value)}/></label></div>
   <div className="flex justify-between items-center"><b>Order items</b><Btn type="button" onClick={addLine}>Add item</Btn></div>
   {lines.map((l,i)=><div key={i} className="grid min-w-0 grid-cols-[minmax(0,1fr)_72px] sm:grid-cols-[minmax(0,1fr)_72px_auto_auto] gap-2 items-end"><label className="min-w-0">Item<select className={f+' min-w-0'} value={l.item} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,item:e.target.value}:x))}>{Object.entries(menu).map(([k,v])=><option key={k} value={k}>{k} · रु. {v.price}</option>)}</select></label><label className="min-w-0">Qty<input type="number" min="1" step="1" className={f} value={l.qty} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,qty:e.target.value}:x))}/></label><div className="pb-2 font-semibold text-right sm:text-left">रु. {(menu[l.item]?.price||0)*(+l.qty||0)}</div>{lines.length>1&&<button type="button" className="pb-2 text-brand text-left sm:text-right" aria-label="Remove item" onClick={()=>setLines(lines.filter((_,j)=>j!==i))}>Remove</button>}</div>)}
   <div className="grid sm:grid-cols-2 gap-3"><label>Cash received (रु.)<input type="number" min="0" max={total} step="0.01" className={f} value={cash} onChange={e=>setCash(e.target.value)}/></label><label>QR received (रु.)<input type="number" min="0" max={total} step="0.01" className={f} value={qr} onChange={e=>setQr(e.target.value)}/></label><label>Online / bank method<select className={f} value={digitalMethod} onChange={e=>setDigitalMethod(e.target.value)}><option>eSewa</option><option>Khalti</option><option>Fonepay</option><option>Bank transfer</option><option>Other</option></select><span className="sr-only">Online payment amount</span><input aria-label="Online or bank payment received in rupees" type="number" min="0" max={total} step="0.01" className={f} value={digital} onChange={e=>setDigital(e.target.value)}/></label></div>
   <label>Discount (रु.)<input type="number" min="0" max={subtotal} step="0.01" className={f} value={discount} onChange={e=>setDiscount(e.target.value)}/></label>
   <div className="rounded-lg bg-cream-100 p-3 grid grid-cols-2 sm:grid-cols-3 gap-2"><div>Subtotal<b className="block">रु. {subtotal}</b></div><div>Discount<b className="block">− रु. {discountAmount}</b></div><div>VAT{settings?.vatEnabled?` (${settings.vatRate}%)`:''}<b className="block">रु. {vat}</b></div><div>Total<b className="block">रु. {total}</b></div><div>Paid<b className="block text-leaf">रु. {paid}</b></div><div>Balance due<b className="block text-brand">रु. {Math.max(0,total-paid)}</b></div><div className="col-span-2 sm:col-span-3 text-xs text-stone-600">{short.length?'Low stock: '+short.join(', '):'Raw materials: '+Object.entries(need).map(([k,v])=>`${k} ${v}`).join(' · ')||'No additional raw materials required'}{Object.entries(finishedUses).some(([,n])=>n>0)&&` · Prepared meals used: ${Object.entries(finishedUses).filter(([,n])=>n>0).map(([k,n])=>`${k} ${n}`).join(', ')}`}</div></div>
   {error&&<div role="alert" className="rounded-lg bg-brand/10 text-brand p-3">{error}</div>}{warn&&<div role="alert" className="rounded-lg bg-brand/10 text-brand p-3 font-semibold">Insufficient stock for {short.join(', ')}. This order can be recorded, but available inventory will not go below zero.</div>}
   <div className="flex gap-2 justify-end"><Btn type="button" c="bg-white border border-cream-300" onClick={close}>Cancel</Btn><Btn type="button" onClick={go}>Generate bill</Btn></div></div></div></div>;
}
