import {useState} from 'react';
import {Card,Btn,Table} from './ui';

const fld='w-full min-w-0 border border-cream-300 bg-white rounded-lg px-3 py-2';
const np=n=>`रु. ${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;

export function StockControl({stock,moves,onMove}){
 const [name,setName]=useState(stock[0]?.name||''),[type,setType]=useState('Stock in'),[qty,setQty]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState('');
 const valuation=stock.reduce((n,s)=>n+s.qty*(s.averageCost||0),0);
 const submit=e=>{e.preventDefault();if(!onMove(name,type,qty,reason)){setError('Enter a valid quantity and reason. Stock cannot go below zero.');return}setQty('');setReason('');setError('')};
 return <><div className="mb-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-cream-300 bg-cream-50 p-4"><span className="text-sm text-stone-600">Recorded ingredients</span><b className="block text-xl">{stock.length}</b></div><div className="rounded-xl border border-cream-300 bg-cream-50 p-4"><span className="text-sm text-stone-600">Estimated stock value</span><b className="block text-xl">{np(valuation)}</b><small>Uses weighted average purchase cost; opening stock without cost is excluded.</small></div></div><Card title="Stock adjustment & wastage"><form onSubmit={submit} className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3 items-end"><label className="text-sm">Ingredient<select className={fld} value={name} onChange={e=>setName(e.target.value)}>{stock.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label className="text-sm">Movement<select className={fld} value={type} onChange={e=>setType(e.target.value)}>{['Stock in','Stock out','Wastage','Customer return','Adjustment'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm">{type==='Adjustment'?'New on-hand quantity':'Quantity'}<input required type="number" min="0.01" step="any" className={fld} value={qty} onChange={e=>setQty(e.target.value)}/></label><label className="text-sm">Reason / reference<input required maxLength="120" className={fld} placeholder="e.g. damaged stock" value={reason} onChange={e=>setReason(e.target.value)}/></label><Btn type="submit">Record movement</Btn></form>{error&&<p role="alert" className="mt-2 text-sm text-brand">{error}</p>}</Card><Card title="Recent stock movement history" cls="mt-4"><Table head={['Date','Ingredient','Movement','Quantity','Reference']}>{moves.slice().reverse().slice(0,100).map(m=><tr key={m.id}><td>{new Date(m.at).toLocaleString('ne-NP',{timeZone:'Asia/Kathmandu'})}</td><td className="font-semibold">{m.name}</td><td>{m.type}</td><td>{m.delta>0?'+':''}{m.delta} {m.unit}</td><td>{m.reason||m.reference||'—'}</td></tr>)}</Table></Card></>
}

export function SupplierPurchases({stock,suppliers,purchases,onSupplier,onPurchase}){
 const [supplier,setSupplier]=useState(suppliers[0]?.id||''),[supplierName,setSupplierName]=useState(''),[phone,setPhone]=useState(''),[item,setItem]=useState(stock[0]?.name||''),[qty,setQty]=useState(''),[cost,setCost]=useState(''),[error,setError]=useState('');
 const addSupplier=e=>{e.preventDefault();if(!supplierName.trim())return setError('Enter a supplier name.');const s=onSupplier({name:supplierName.trim(),phone:phone.trim()});setSupplier(String(s.id));setSupplierName('');setPhone('');setError('')};
 const purchase=e=>{e.preventDefault();const q=Number(qty),c=Number(cost);if(!supplier||!Number.isFinite(q)||q<=0||!Number.isFinite(c)||c<0){setError('Select a supplier and enter a valid quantity and unit cost.');return}if(!onPurchase(supplier,item,q,c)){setError('Could not record this purchase.');return}setQty('');setCost('');setError('')};
 return <><div className="grid lg:grid-cols-2 gap-4"><Card title="Supplier register"><form onSubmit={addSupplier} className="grid gap-3"><label className="text-sm">Supplier name<input required className={fld} value={supplierName} onChange={e=>setSupplierName(e.target.value)} placeholder="Business or contact name"/></label><label className="text-sm">Phone<input type="tel" className={fld} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+977…"/></label><Btn type="submit">Add supplier</Btn></form><div className="mt-4"><Table head={['Supplier','Phone']}>{suppliers.map(s=><tr key={s.id}><td className="font-semibold">{s.name}</td><td>{s.phone||'—'}</td></tr>)}</Table></div></Card><Card title="Record ingredient purchase"><form onSubmit={purchase} className="grid gap-3"><label className="text-sm">Supplier<select required className={fld} value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">Choose supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="text-sm">Ingredient<select className={fld} value={item} onChange={e=>setItem(e.target.value)}>{stock.map(s=><option key={s.name}>{s.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-sm">Quantity<input required type="number" min="0.01" step="any" className={fld} value={qty} onChange={e=>setQty(e.target.value)}/></label><label className="text-sm">Unit cost (रु.)<input required type="number" min="0" step="0.01" className={fld} value={cost} onChange={e=>setCost(e.target.value)}/></label></div><p className="text-sm text-stone-600">Purchase total: <b>{np((+qty||0)*(+cost||0))}</b></p><Btn type="submit">Save purchase & receive stock</Btn></form></Card></div><Card title="Purchase history" cls="mt-4"><Table head={['Date','Supplier','Ingredient','Quantity','Total cost']}>{purchases.slice().reverse().map(p=><tr key={p.id}><td>{new Date(p.at).toLocaleString('ne-NP',{timeZone:'Asia/Kathmandu'})}</td><td>{suppliers.find(s=>s.id===p.supplierId)?.name||'Supplier removed'}</td><td>{p.item}</td><td>{p.qty}</td><td>{np(p.qty*p.unitCost)}</td></tr>)}</Table></Card>{error&&<p role="alert" className="mt-3 text-sm text-brand">{error}</p>}</>
}

export function Expenses({expenses,onAdd}){
 const [category,setCategory]=useState('Ingredients'),[note,setNote]=useState(''),[amount,setAmount]=useState(''),[method,setMethod]=useState('Cash'),[error,setError]=useState('');
 const total=expenses.reduce((a,e)=>a+Number(e.amount||0),0);
 const submit=e=>{e.preventDefault();const n=Number(amount);if(!Number.isFinite(n)||n<=0||!note.trim()){setError('Add a description and a positive amount.');return}onAdd({category,note:note.trim(),amount:n,method});setAmount('');setNote('');setError('')};
 return <><Card title="Record business expense"><form onSubmit={submit} className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3 items-end"><label className="text-sm">Category<select className={fld} value={category} onChange={e=>setCategory(e.target.value)}>{['Ingredients','Packaging','Delivery / fuel','Rent','Utilities','Staff','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm">Description<input required maxLength="120" className={fld} value={note} onChange={e=>setNote(e.target.value)}/></label><label className="text-sm">Amount (रु.)<input required type="number" min="0.01" step="0.01" className={fld} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="text-sm">Paid by<select className={fld} value={method} onChange={e=>setMethod(e.target.value)}><option>Cash</option><option>Bank</option><option>QR</option></select></label><Btn type="submit">Save expense</Btn></form>{error&&<p role="alert" className="mt-2 text-sm text-brand">{error}</p>}</Card><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-cream-300 bg-cream-50 p-4"><span className="text-sm text-stone-600">Recorded expenses</span><strong className="block text-xl">{np(total)}</strong></div><div className="rounded-xl border border-cream-300 bg-cream-50 p-4"><span className="text-sm text-stone-600">Entries</span><strong className="block text-xl">{expenses.length}</strong></div></div><Card title="Expense history" cls="mt-4"><Table head={['Date','Category','Description','Paid by','Amount']}>{expenses.slice().reverse().map(e=><tr key={e.id}><td>{new Date(e.at).toLocaleString('ne-NP',{timeZone:'Asia/Kathmandu'})}</td><td>{e.category}</td><td>{e.note}</td><td>{e.method}</td><td>{np(e.amount)}</td></tr>)}</Table></Card></>
}

const dayKey=value=>{const date=new Date(value||Date.now());return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu',year:'numeric',month:'2-digit',day:'2-digit'}).format(Number.isNaN(date.getTime())?new Date():date)};
export function Reports({orders,expenses,purchases,moves=[]}){
 const today=dayKey(new Date()),[period,setPeriod]=useState('Daily'),[from,setFrom]=useState(today),[to,setTo]=useState(today);
 const range=(()=>{const end=new Date(`${today}T00:00:00Z`),start=new Date(end);if(period==='Weekly')start.setUTCDate(start.getUTCDate()-6);if(period==='Monthly')start.setUTCDate(1);return {from:period==='Custom'?from:dayKey(start),to:period==='Custom'?to:today}})();
 const inRange=x=>{const key=dayKey(x||new Date());return key>=range.from&&key<=range.to};
 const sold=orders.filter(o=>o.status!=='Cancelled'&&inRange(o.createdAt)),paid=sold.flatMap(o=>o.payments||[]),spent=expenses.filter(e=>inRange(e.at)),bought=purchases.filter(p=>inRange(p.at)),used=moves.filter(m=>m.delta<0&&inRange(m.at));
 const invoiced=sold.reduce((n,o)=>n+Number(o.amount||0),0),received=paid.reduce((n,p)=>n+Number(p.amount||0),0),expenseTotal=spent.reduce((n,e)=>n+Number(e.amount||0),0),purchaseTotal=bought.reduce((n,p)=>n+Number(p.qty||0)*Number(p.unitCost||0),0);
 return <><Card title="Sales, collection & expense reports"><div className="flex flex-wrap items-end gap-3 mb-4"><label className="text-sm">Period<select className="block rounded-lg border border-cream-300 bg-white px-3 py-2" value={period} onChange={e=>setPeriod(e.target.value)}>{['Daily','Weekly','Monthly','Custom'].map(x=><option key={x}>{x}</option>)}</select></label>{period==='Custom'&&<><label className="text-sm">From<input type="date" className="block rounded-lg border border-cream-300 bg-white px-3 py-2" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">To<input type="date" className="block rounded-lg border border-cream-300 bg-white px-3 py-2" value={to} onChange={e=>setTo(e.target.value)}/></label></>}<span className="text-sm text-stone-500">{range.from} to {range.to} · Nepal time</span></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><div className="rounded-xl border border-cream-300 p-3"><span className="text-sm">Invoices</span><b className="block">{np(invoiced)}</b><small>{sold.length} orders</small></div><div className="rounded-xl border border-cream-300 p-3"><span className="text-sm">Payments received</span><b className="block">{np(received)}</b></div><div className="rounded-xl border border-cream-300 p-3"><span className="text-sm">Expenses</span><b className="block">{np(expenseTotal)}</b></div><div className="rounded-xl border border-cream-300 p-3"><span className="text-sm">Purchases</span><b className="block">{np(purchaseTotal)}</b></div></div><div className="mt-4"><Table head={['Payment method','Amount received']}>{[...new Set(paid.map(p=>p.method))].map(m=><tr key={m}><td>{m}</td><td>{np(paid.filter(p=>p.method===m).reduce((n,p)=>n+Number(p.amount||0),0))}</td></tr>)}{!paid.length&&<tr><td colSpan="2" className="text-stone-500">No collections in this period.</td></tr>}</Table></div><div className="mt-4"><Table head={['Stock used / lost','Quantity']}>{[...new Set(used.map(m=>m.name))].map(name=><tr key={name}><td>{name}</td><td>{used.filter(m=>m.name===name).reduce((n,m)=>n-m.delta,0)} {used.find(m=>m.name===name)?.unit}</td></tr>)}{!used.length&&<tr><td colSpan="2" className="text-stone-500">No stock usage or loss in this period.</td></tr>}</Table></div><p className="mt-3 text-xs text-stone-500">This report summarizes recorded transactions; it is not an accounting ledger or a profit calculation.</p></Card></>
}

export function StaffDetails({staff,onSave,onDelete}){
 const [form,setForm]=useState({name:'',department:'Reception',contact:'',address:'',bank:'',photo:''});
 const field='w-full border border-cream-300 rounded-lg px-3 py-2 bg-white';
 const submit=e=>{e.preventDefault();if(!form.name.trim())return;onSave({...form,id:crypto.randomUUID()});setForm({name:'',department:'Reception',contact:'',address:'',bank:'',photo:''})};
 return <><Card title="Add staff member"><form onSubmit={submit} className="grid sm:grid-cols-2 gap-3">{[['name','Full name'],['contact','Contact number'],['address','Address'],['bank','Bank details']].map(([k,label])=><label key={k} className="text-sm">{label}<input className={field} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="text-sm">Department<select className={field} value={form.department} onChange={e=>setForm({...form,department:e.target.value})}>{['Reception','Kitchen','Delivery','Accounts','Administration','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm">Photo<input type="file" accept="image/*" className={field} onChange={e=>{const f=e.target.files?.[0];if(f){const reader=new FileReader();reader.onload=()=>setForm(v=>({...v,photo:reader.result}));reader.readAsDataURL(f)}}}/></label><Btn type="submit" className="sm:col-span-2">Save staff details</Btn></form></Card><Card title="Staff directory" cls="mt-4" right={<Btn c="bg-navy text-white" onClick={()=>downloadCsv('staff-details',staff,[['Name','name'],['Department','department'],['Contact','contact'],['Address','address'],['Bank details','bank']])}>Export data</Btn>}><Table head={['Photo','Name','Department','Contact','Address','Bank details','Action']}>{staff.map(s=><tr key={s.id}><td>{s.photo?<img src={s.photo} alt={s.name} className="w-12 h-12 rounded-full object-cover"/>:'—'}</td><td className="font-semibold">{s.name}</td><td>{s.department}</td><td>{s.contact}</td><td>{s.address}</td><td>{s.bank}</td><td><Btn c="bg-white border border-brand text-brand" onClick={()=>onDelete(s.id)}>Remove</Btn></td></tr>)}</Table></Card></>
}

export function MenuEditor({menu,stock=[],onSave}){
 const [name,setName]=useState(''),[price,setPrice]=useState(''),[category,setCategory]=useState('Daily nasta'),[pending,setPending]=useState({});
 const save=(n,patch)=>onSave({...menu,[n]:{...menu[n],...patch}});
 const addIngredient=(n,ing)=>{if(!ing)return;save(n,{r:{...(menu[n]?.r||{}),[ing]:1}});setPending(p=>({...p,[n]:''}))};
 const dropIngredient=(n,ing)=>{const r={...(menu[n]?.r||{})};delete r[ing];save(n,{r})};
 const chip='w-full min-w-0 border border-cream-300 bg-white rounded-lg px-2 py-1';
 return <Card title="Order categories and menu" cls="mt-4"><p className="text-sm text-stone-600 mb-3">Everything here is entered by you: add the items you sell, their price and the ingredients used per box. Changes apply to new orders immediately.</p>{Object.keys(menu).length?<div className="grid sm:grid-cols-3 gap-2 mb-4">{Object.entries(menu).map(([n,p])=><div key={n} className="text-sm rounded-lg border border-cream-300 p-2"><div className="font-semibold break-words">{n}</div><div className="flex gap-2 mt-1"><select className={chip} aria-label={`Category for ${n}`} value={p.category||'Lunch menu'} onChange={e=>save(n,{category:e.target.value})}><option>Lunch menu</option><option>Daily nasta</option></select><input aria-label={`${n} price`} className={chip+' w-24'} type="number" min="0" value={p.price} onChange={e=>save(n,{price:Number(e.target.value)})}/><button type="button" className="text-brand text-xs" onClick={()=>{const x={...menu};delete x[n];onSave(x)}}>Remove</button></div><div className="mt-2 border-t border-cream-200 pt-2"><span className="text-xs font-semibold text-stone-500">Ingredients used per box</span>{Object.entries(p.r||{}).map(([ing,q])=><div key={ing} className="flex items-center gap-1.5 mt-1 text-xs"><span className="flex-1 min-w-0 break-words">{ing} <span className="text-stone-400">{stock.find(s=>s.name===ing)?.u||''}</span></span><input aria-label={`${ing} per box for ${n}`} className={chip+' w-20'} type="number" min="0" step="any" value={q} onChange={e=>save(n,{r:{...(p.r||{}),[ing]:Number(e.target.value)}})}/><button type="button" className="text-brand" aria-label={`Remove ${ing}`} onClick={()=>dropIngredient(n,ing)}>×</button></div>)}{stock.length?<select className={chip+' mt-2 text-xs'} aria-label={`Add ingredient to ${n}`} value={pending[n]||''} onChange={e=>addIngredient(n,e.target.value)}><option value="">Add ingredient…</option>{stock.filter(s=>!(p.r||{})[s.name]).map(s=><option key={s.name}>{s.name}</option>)}</select>:<p className="text-xs text-stone-500 mt-1">Add ingredients on the Inventory page to link them to this item.</p>}</div></div>)}</div>:<p className="text-sm text-stone-500 mb-4">No menu items yet. Add your first item below.</p>}<form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();if(!name.trim()||price==='')return;onSave({...menu,[name.trim()]:{price:Number(price),category,r:{}}});setName('');setPrice('')}}><input className="rounded-lg border border-cream-300 px-3 py-2" placeholder="Item name" value={name} onChange={e=>setName(e.target.value)} required/><input className="w-28 rounded-lg border border-cream-300 px-3 py-2" type="number" min="0" placeholder="Price" value={price} onChange={e=>setPrice(e.target.value)} required/><select className="rounded-lg border border-cream-300 px-3 py-2" value={category} onChange={e=>setCategory(e.target.value)}><option>Lunch menu</option><option>Daily nasta</option></select><Btn type="submit">Add menu item</Btn></form></Card>
}

export function CustomerOrderHistory({customers,orders}){const [q,setQ]=useState('');const rows=orders.filter(o=>o.status!=='Cancelled'&&(!q||`${customers.find(c=>c.id===o.c)?.name||''} ${customers.find(c=>c.id===o.c)?.phone||''} ${o.id}`.toLowerCase().includes(q.toLowerCase()))).slice().reverse().map(o=>({customer:customers.find(c=>c.id===o.c)?.name||'Customer removed',phone:customers.find(c=>c.id===o.c)?.phone||'',invoice:o.id,orderedAt:o.createdAt||'',items:(o.lines||[{item:o.item,qty:o.qty}]).map(x=>`${x.qty} x ${x.item}`).join(', '),qty:o.qty,total:o.amount}));return <Card title="Per customer order history" cls="mt-4" right={<Btn c="bg-navy text-white" onClick={()=>downloadCsv('customer-orders',rows,[['Customer','customer'],['Phone','phone'],['Invoice','invoice'],['Ordered at','orderedAt'],['Items','items'],['Quantity','qty'],['Total','total']])}>Export data</Btn>}><input className="w-full sm:max-w-sm rounded-lg border border-cream-300 px-3 py-2 mb-3" placeholder="Search customer, phone or invoice" value={q} onChange={e=>setQ(e.target.value)}/><Table head={['Customer','Invoice','When ordered','Items','Quantity','Order total']}>{rows.map((o,i)=><tr key={o.invoice+i}><td className="font-semibold">{o.customer}<small className="block text-stone-500">{o.phone}</small></td><td>{o.invoice}</td><td>{o.orderedAt?new Date(o.orderedAt).toLocaleString('ne-NP',{timeZone:'Asia/Kathmandu'}):'—'}</td><td>{o.items}</td><td>{o.qty}</td><td>{np(o.total)}</td></tr>)}</Table></Card>}

export function CustomerFavorites({customers,orders}){
 const today=new Date(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())+'T00:00:00Z');
 const days=Array.from({length:7},(_,i)=>{const d=new Date(today);d.setUTCDate(d.getUTCDate()-i);return d.toISOString().slice(0,10)}),valid=new Set(days);
 const dateInKathmandu=value=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value||Date.now()));
 const rows=customers.map(c=>{const recent=orders.filter(o=>o.c===c.id&&o.status!=='Cancelled'&&valid.has(dateInKathmandu(o.createdAt))),activeDays=new Set(recent.map(o=>dateInKathmandu(o.createdAt)));return {c,orders:recent,activeDays:activeDays.size,total:recent.reduce((n,o)=>n+Number(o.amount||0),0)}}).filter(x=>x.activeDays>=3).sort((a,b)=>b.activeDays-a.activeDays||b.orders.length-a.orders.length);
 return <Card title="Frequent ordering customers" right={<Btn c="bg-navy text-white" onClick={()=>downloadCsv('customer-favorites',rows.map(x=>({name:x.c.name,phone:x.c.phone,days:x.activeDays,orders:x.orders.length,total:x.total})),[['Customer','name'],['Phone','phone'],['Order days in last 7','days'],['Orders in last 7 days','orders'],['Order total','total']])}>Export data</Btn>}><p className="text-sm text-stone-600 mb-3">Customers with orders on at least 3 distinct days in the last 7 days. Daily regulars ordered on 5 or more days.</p><Table head={['Customer','Phone','Days ordered','Orders this week','Total this week','Pattern']}>{rows.map(({c,activeDays,orders,total})=><tr key={c.id}><td className="font-semibold">{c.name}</td><td>{c.phone}</td><td>{activeDays} / 7</td><td>{orders.length}</td><td>{np(total)}</td><td><span className="rounded-full bg-accent/15 px-2.5 py-1 text-xs font-semibold text-orange-800">{activeDays>=5?'Daily regular':'Frequent'}</span></td></tr>)}</Table>{!rows.length&&<p className="py-5 text-center text-stone-500">Frequent customers will appear here after ordering on 3 different days within a 7 day period.</p>}</Card>
}

export function downloadCsv(name,rows,columns){const esc=x=>'"'+String(x??'').replaceAll('"','""')+'"';const text=[columns.map(x=>esc(x[0])).join(','),...rows.map(r=>columns.map(([,k])=>esc(r[k])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}));a.download=`${name}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}

export function ReminderHistory({reminders,customers,orders}){return <Card title="Customer payment reminder history"><Table head={['Sent at','Customer','Invoices','Amount when sent','Current balance']}>{reminders.slice().reverse().map(r=>{const customer=customers.find(c=>c.id===r.customerId),balance=(r.invoiceIds||[]).reduce((n,id)=>{const o=orders.find(x=>x.id===id);return n+(o&&o.status!=='Cancelled'?Math.max(0,o.amount-(o.payments||[]).reduce((a,p)=>a+Number(p.amount||0),0)):0)},0);return <tr key={r.id}><td>{new Date(r.at).toLocaleString('ne-NP',{timeZone:'Asia/Kathmandu'})}</td><td>{customer?.name||'Customer removed'}</td><td>{(r.invoiceIds||[]).join(', ')}</td><td>{np(r.amount)}</td><td>{np(balance)}{balance===0?' · Cleared':''}</td></tr>})}{!reminders.length&&<tr><td colSpan="5" className="py-5 text-center text-stone-500">No reminders have been prepared yet.</td></tr>}</Table><p className="mt-3 text-xs text-stone-500">Reminder records show when a WhatsApp message was opened for manual sending; delivery status is not verified by a WhatsApp API.</p></Card>}
