import {useState} from 'react';
import {Card,Btn,Table} from './ui';
import {P} from '../data';

const fld='w-full min-w-0 border border-cream-300 bg-white rounded-lg px-3 py-2';
const np=n=>`रु. ${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;

export function StockControl({stock,moves,onMove}){
 const [name,setName]=useState(stock[0]?.name||''),[type,setType]=useState('Stock in'),[qty,setQty]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState('');
 const valuation=stock.reduce((n,s)=>n+s.qty*(s.averageCost||0),0);
 const submit=e=>{e.preventDefault();if(!onMove(name,type,qty,reason)){setError('Enter a valid quantity and reason. Stock cannot go below zero.');return}setQty('');setReason('');setError('')};
 return <><div className="mb-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-cream-300 bg-cream-50 p-4"><span className="text-sm text-stone-600">Recorded ingredients</span><b className="block text-xl">{stock.length}</b></div><div className="rounded-xl border border-cream-300 bg-cream-50 p-4"><span className="text-sm text-stone-600">Estimated stock value</span><b className="block text-xl">{np(valuation)}</b><small>Uses weighted average purchase cost; opening stock without cost is excluded.</small></div></div><Card title="Stock adjustment & wastage"><form onSubmit={submit} className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3 items-end"><label className="text-sm">Ingredient<select className={fld} value={name} onChange={e=>setName(e.target.value)}>{stock.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label className="text-sm">Movement<select className={fld} value={type} onChange={e=>setType(e.target.value)}>{['Stock in','Stock out','Wastage','Customer return','Adjustment'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm">{type==='Adjustment'?'New on-hand quantity':'Quantity'}<input required type="number" min="0.01" step="any" className={fld} value={qty} onChange={e=>setQty(e.target.value)}/></label><label className="text-sm">Reason / reference<input required maxLength="120" className={fld} placeholder="e.g. damaged stock" value={reason} onChange={e=>setReason(e.target.value)}/></label><Btn type="submit">Record movement</Btn></form>{error&&<p role="alert" className="mt-2 text-sm text-brand">{error}</p>}</Card><Card title="Recent stock movement history" cls="mt-4"><Table head={['Date','Ingredient','Movement','Quantity','Reference']}>{moves.slice().reverse().slice(0,100).map(m=><tr key={m.id}><td>{new Date(m.at).toLocaleString('ne-NP',{timeZone:'Asia/Kathmandu'})}</td><td className="font-semibold">{m.name}</td><td>{m.type}</td><td>{m.delta>0?'+':''}{m.delta} {m.unit}</td><td>{m.reason||m.reference||'—'}</td></tr>)}</Table></Card></>
}

export function KitchenProduction({stock,finishedStock,onProduce}){
 const [item,setItem]=useState(Object.keys(P)[0]),[qty,setQty]=useState('1'),[error,setError]=useState('');
 const plan=Object.entries(P[item].r).map(([name,perUnit])=>({name,perUnit,needed:perUnit*(Number(qty)||0),available:stock.find(s=>s.name===name)?.qty||0})),short=plan.filter(x=>x.needed>x.available);
 const submit=e=>{e.preventDefault();if(!Number.isInteger(+qty)||+qty<1){setError('Enter a whole number of boxes to prepare.');return}if(short.length){setError(`Insufficient ingredients: ${short.map(x=>x.name).join(', ')}.`);return}if(!onProduce(item,+qty)){setError('Production could not be recorded.');return}setQty('');setError('')};
 return <><div className="grid lg:grid-cols-2 gap-4"><Card title="Finished meal stock"><Table head={['Product','Ready boxes','Selling price']}>{Object.keys(P).map(k=><tr key={k}><td className="font-semibold">{k}</td><td>{finishedStock[k]||0} boxes</td><td>{np(P[k].price)}</td></tr>)}</Table></Card><Card title="Prepare a kitchen batch"><form onSubmit={submit} className="grid gap-3"><label className="text-sm">Product<select className={fld} value={item} onChange={e=>setItem(e.target.value)}>{Object.keys(P).map(k=><option key={k}>{k}</option>)}</select></label><label className="text-sm">Number of boxes<input type="number" min="1" step="1" className={fld} value={qty} onChange={e=>setQty(e.target.value)}/></label><p className="text-sm font-semibold">Ingredients required</p>{plan.map(x=><div key={x.name} className="flex justify-between gap-3 border-b border-cream-200 pb-1 text-sm"><span>{x.name}</span><span>{x.needed} {stock.find(s=>s.name===x.name)?.u} · {x.available} available</span></div>)}{error&&<p role="alert" className="text-sm text-brand">{error}</p>}<Btn type="submit">Record production & add finished stock</Btn></form></Card></div></>
}

export function SupplierPurchases({stock,suppliers,purchases,onSupplier,onPurchase}){
 const [supplier,setSupplier]=useState(suppliers[0]?.id||''),[supplierName,setSupplierName]=useState(''),[phone,setPhone]=useState(''),[item,setItem]=useState(stock[0]?.name||''),[qty,setQty]=useState(''),[cost,setCost]=useState(''),[error,setError]=useState('');
 const addSupplier=e=>{e.preventDefault();if(!supplierName.trim())return setError('Enter a supplier name.');const s=onSupplier({name:supplierName.trim(),phone:phone.trim()});setSupplier(String(s.id));setSupplierName('');setPhone('');setError('')};
 const purchase=e=>{e.preventDefault();const q=Number(qty),c=Number(cost);if(!supplier||!Number.isFinite(q)||q<=0||!Number.isFinite(c)||c<0){setError('Select a supplier and enter a valid quantity and unit cost.');return}if(!onPurchase(supplier,item,q,c)){setError('Could not record this purchase.');return}setQty('');setCost('');setError('')};
 return <><div className="grid lg:grid-cols-2 gap-4"><Card title="Supplier register"><form onSubmit={addSupplier} className="grid gap-3"><label className="text-sm">Supplier name<input required className={fld} value={supplierName} onChange={e=>setSupplierName(e.target.value)} placeholder="Business or contact name"/></label><label className="text-sm">Phone<input type="tel" className={fld} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+977…"/></label><Btn type="submit">Add supplier</Btn></form><div className="mt-4"><Table head={['Supplier','Phone']}>{suppliers.map(s=><tr key={s.id}><td className="font-semibold">{s.name}</td><td>{s.phone||'—'}</td></tr>)}</Table></div></Card><Card title="Record ingredient purchase"><form onSubmit={purchase} className="grid gap-3"><label className="text-sm">Supplier<select required className={fld} value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">Choose supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="text-sm">Ingredient<select className={fld} value={item} onChange={e=>setItem(e.target.value)}>{stock.map(s=><option key={s.name}>{s.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-sm">Quantity<input required type="number" min="0.01" step="any" className={fld} value={qty} onChange={e=>setQty(e.target.value)}/></label><label className="text-sm">Unit cost (रु.)<input required type="number" min="0" step="0.01" className={fld} value={cost} onChange={e=>setCost(e.target.value)}/></label></div><p className="text-sm text-stone-600">Purchase total: <b>{np((+qty||0)*(+cost||0))}</b></p><Btn type="submit">Save purchase & receive stock</Btn></form></Card></div><Card title="Purchase history" cls="mt-4"><Table head={['Date','Supplier','Ingredient','Quantity','Total cost']}>{purchases.slice().reverse().map(p=><tr key={p.id}><td>{new Date(p.at).toLocaleString('ne-NP',{timeZone:'Asia/Kathmandu'})}</td><td>{suppliers.find(s=>s.id===p.supplierId)?.name||'Supplier removed'}</td><td>{p.item}</td><td>{p.qty}</td><td>{np(p.qty*p.unitCost)}</td></tr>)}</Table></Card>{error&&<p role="alert" className="mt-3 text-sm text-brand">{error}</p>}</>
}

export function Expenses({expenses,onAdd}){
 const [category,setCategory]=useState('Ingredients'),[note,setNote]=useState(''),[amount,setAmount]=useState(''),[method,setMethod]=useState('Cash'),[error,setError]=useState('');
 const total=expenses.reduce((a,e)=>a+Number(e.amount||0),0);
 const submit=e=>{e.preventDefault();const n=Number(amount);if(!Number.isFinite(n)||n<=0||!note.trim()){setError('Add a description and a positive amount.');return}onAdd({category,note:note.trim(),amount:n,method});setAmount('');setNote('');setError('')};
 return <><Card title="Record business expense"><form onSubmit={submit} className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3 items-end"><label className="text-sm">Category<select className={fld} value={category} onChange={e=>setCategory(e.target.value)}>{['Ingredients','Packaging','Delivery / fuel','Rent','Utilities','Staff','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm">Description<input required maxLength="120" className={fld} value={note} onChange={e=>setNote(e.target.value)}/></label><label className="text-sm">Amount (रु.)<input required type="number" min="0.01" step="0.01" className={fld} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="text-sm">Paid by<select className={fld} value={method} onChange={e=>setMethod(e.target.value)}><option>Cash</option><option>Bank</option><option>QR</option></select></label><Btn type="submit">Save expense</Btn></form>{error&&<p role="alert" className="mt-2 text-sm text-brand">{error}</p>}</Card><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-cream-300 bg-cream-50 p-4"><span className="text-sm text-stone-600">Recorded expenses</span><strong className="block text-xl">{np(total)}</strong></div><div className="rounded-xl border border-cream-300 bg-cream-50 p-4"><span className="text-sm text-stone-600">Entries</span><strong className="block text-xl">{expenses.length}</strong></div></div><Card title="Expense history" cls="mt-4"><Table head={['Date','Category','Description','Paid by','Amount']}>{expenses.slice().reverse().map(e=><tr key={e.id}><td>{new Date(e.at).toLocaleString('ne-NP',{timeZone:'Asia/Kathmandu'})}</td><td>{e.category}</td><td>{e.note}</td><td>{e.method}</td><td>{np(e.amount)}</td></tr>)}</Table></Card></>
}

const dayKey=value=>{const date=new Date(value||Date.now());return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu',year:'numeric',month:'2-digit',day:'2-digit'}).format(Number.isNaN(date.getTime())?new Date():date)};
export function Reports({orders,expenses,purchases,moves=[]}){
 const today=dayKey(new Date()),[period,setPeriod]=useState('Daily'),[from,setFrom]=useState(today),[to,setTo]=useState(today);
 const range=(()=>{const end=new Date(`${today}T00:00:00Z`),start=new Date(end);if(period==='Weekly')start.setUTCDate(start.getUTCDate()-6);if(period==='Monthly')start.setUTCDate(1);return {from:period==='Custom'?from:dayKey(start),to:period==='Custom'?to:today}})();
 const inRange=x=>{const key=dayKey(x||new Date());return key>=range.from&&key<=range.to};
 const sold=orders.filter(o=>o.status!=='Cancelled'&&inRange(o.createdAt)),paid=sold.flatMap(o=>o.payments||[]),spent=expenses.filter(e=>inRange(e.at)),bought=purchases.filter(p=>inRange(p.at)),used=moves.filter(m=>m.delta<0&&inRange(m.at));
 const invoiced=sold.reduce((n,o)=>n+Number(o.amount||0),0),received=paid.reduce((n,p)=>n+Number(p.amount||0),0),expenseTotal=spent.reduce((n,e)=>n+Number(e.amount||0),0),purchaseTotal=bought.reduce((n,p)=>n+Number(p.qty||0)*Number(p.unitCost||0),0);
 return <><Card title="Sales, collection & expense reports"><div className="flex flex-wrap items-end gap-3 mb-4"><label className="text-sm">Period<select className="block rounded-lg border border-cream-300 bg-white px-3 py-2" value={period} onChange={e=>setPeriod(e.target.value)}>{['Daily','Weekly','Monthly','Custom'].map(x=><option key={x}>{x}</option>)}</select></label>{period==='Custom'&&<><label className="text-sm">From<input type="date" className="block rounded-lg border border-cream-300 bg-white px-3 py-2" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">To<input type="date" className="block rounded-lg border border-cream-300 bg-white px-3 py-2" value={to} onChange={e=>setTo(e.target.value)}/></label></>}<span className="text-sm text-stone-500">{range.from} to {range.to} · Nepal time</span></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><div className="rounded-xl border border-cream-300 p-3"><span className="text-sm">Invoices</span><b className="block">{np(invoiced)}</b><small>{sold.length} orders</small></div><div className="rounded-xl border border-cream-300 p-3"><span className="text-sm">Payments received</span><b className="block">{np(received)}</b></div><div className="rounded-xl border border-cream-300 p-3"><span className="text-sm">Expenses</span><b className="block">{np(expenseTotal)}</b></div><div className="rounded-xl border border-cream-300 p-3"><span className="text-sm">Purchases</span><b className="block">{np(purchaseTotal)}</b></div></div><div className="mt-4"><Table head={['Payment method','Amount received']}>{[...new Set(paid.map(p=>p.method))].map(m=><tr key={m}><td>{m}</td><td>{np(paid.filter(p=>p.method===m).reduce((n,p)=>n+Number(p.amount||0),0))}</td></tr>)}{!paid.length&&<tr><td colSpan="2" className="text-stone-500">No collections in this period.</td></tr>}</Table></div><div className="mt-4"><Table head={['Stock used / lost','Quantity']}>{[...new Set(used.map(m=>m.name))].map(name=><tr key={name}><td>{name}</td><td>{used.filter(m=>m.name===name).reduce((n,m)=>n-m.delta,0)} {used.find(m=>m.name===name)?.unit}</td></tr>)}{!used.length&&<tr><td colSpan="2" className="text-stone-500">No stock usage or loss in this period.</td></tr>}</Table></div><p className="mt-3 text-xs text-stone-500">This report summarizes recorded transactions; it is not an accounting ledger or a profit calculation.</p></Card></>
}

export function StaffAccess(){return <Card title="Demo staff accounts"><p className="mb-3 text-sm text-stone-600">These accounts are hard-coded for this local demo. A real deployment must replace them with server-side authentication and permissions; do not use these passwords in production.</p><Table head={['Role','Username','Demo password','Access scope']}><tr><td>Administrator</td><td>admin</td><td>admin123</td><td>All demo modules</td></tr><tr><td>Reception</td><td>reception</td><td>reception123</td><td>Orders, billing, delivery, customers</td></tr><tr><td>Delivery</td><td>driver1 / driver2</td><td>driver123</td><td>Assigned deliveries only</td></tr></Table></Card>}

export function ReminderHistory({reminders,customers,orders}){return <Card title="Customer payment reminder history"><Table head={['Sent at','Customer','Invoices','Amount when sent','Current balance']}>{reminders.slice().reverse().map(r=>{const customer=customers.find(c=>c.id===r.customerId),balance=(r.invoiceIds||[]).reduce((n,id)=>{const o=orders.find(x=>x.id===id);return n+(o&&o.status!=='Cancelled'?Math.max(0,o.amount-(o.payments||[]).reduce((a,p)=>a+Number(p.amount||0),0)):0)},0);return <tr key={r.id}><td>{new Date(r.at).toLocaleString('ne-NP',{timeZone:'Asia/Kathmandu'})}</td><td>{customer?.name||'Customer removed'}</td><td>{(r.invoiceIds||[]).join(', ')}</td><td>{np(r.amount)}</td><td>{np(balance)}{balance===0?' · Cleared':''}</td></tr>})}{!reminders.length&&<tr><td colSpan="5" className="py-5 text-center text-stone-500">No reminders have been prepared yet.</td></tr>}</Table><p className="mt-3 text-xs text-stone-500">Reminder records show when a WhatsApp message was opened for manual sending; delivery status is not verified by a WhatsApp API.</p></Card>}
