import {useEffect,useRef,useState} from 'react';
import {STAT,SC,fmt,NAV} from './data';
import {Badge,Card,Btn,Table,Stat} from './components/ui';
import LOGO from './assets/logo.jpg';
import Login from './components/Login';
import NewOrder from './components/NewOrder';
import InvoiceDocument from './components/InvoiceDocument';
import UserAccounts from './components/UserAccounts';
import {StockControl,SupplierPurchases,Expenses,Reports,StaffDetails,CustomerOrderHistory,CustomerFavorites,MenuEditor,ReminderHistory,downloadCsv} from './components/Operations';

const DEFAULT_SETTINGS={businessName:'Hamro Lunch Box',address:'',phone:'',pan:'',vatNumber:'',vatEnabled:false,vatRate:13,qrLabel:'Scan to pay'};
const EMPTY_DATA={orders:[],stock:[],customers:[],next:1,menu:{},staff:[],finishedStock:{},productionRuns:[],stockMoves:[],suppliers:[],purchases:[],expenses:[],reminders:[],settings:DEFAULT_SETTINGS};
const api=async(path,options={})=>{const response=await fetch('/api'+path,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const body=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(body.error||'Request failed'),{status:response.status});return body};
const money=n=>`रु. ${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const nepalDate=value=>new Intl.DateTimeFormat('ne-NP',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kathmandu'}).format(new Date(value));
const paidOf=o=>(o.payments||[]).reduce((a,p)=>a+(+p.amount||0),0);
const methodOf=o=>{const ms=[...new Set((o.payments||[]).map(p=>p.method))];return ms.length?ms.join(' + '):'Unpaid'};
export default function App(){
 const [user,setUser]=useState(null),[authReady,setAuthReady]=useState(false),[page,setPage]=useState('dash'),[data,setData]=useState(null),[accounts,setAccounts]=useState([]),[toast,setToast]=useState(null),[modal,setModal]=useState(false),[dir,setDir]=useState('All'),[search,setSearch]=useState(''),[receipt,setReceipt]=useState(null),[receive,setReceive]=useState(null),[payment,setPayment]=useState(null),[statusFilter,setStatusFilter]=useState('All');
 const revision=useRef(0),saveQueue=useRef(Promise.resolve()),lastSynced=useRef('');
 const loadData=async()=>{const result=await api('/business');const loaded={...EMPTY_DATA,...result.data,settings:{...DEFAULT_SETTINGS,...(result.data.settings||{})}};setData(loaded);revision.current=result.revision||0;lastSynced.current=JSON.stringify(loaded)};
 useEffect(()=>{(async()=>{try{const {user:u}=await api('/auth/me');setUser(u);setPage(NAV[u.role][0][0]);await loadData();if(u.role!=='delivery')setAccounts((await api('/auth/users')).users)}catch{}finally{setAuthReady(true)}})()},[]);
 useEffect(()=>{if(!user||!data||user.role==='delivery')return;const payload=JSON.stringify(data);if(payload===lastSynced.current)return;const timer=setTimeout(()=>{saveQueue.current=saveQueue.current.then(async()=>{const result=await api('/business',{method:'PUT',body:JSON.stringify({data:JSON.parse(payload),revision:revision.current})});revision.current=result.revision;lastSynced.current=payload}).catch(err=>{setToast({t:err.status===409?'Data changed in another session':'Save failed',m:err.message});if(err.status===401){setUser(null);setData(null)}})},350);return()=>clearTimeout(timer)},[data,user]);
 const update=(fn)=>setData(d=>fn(d));
 const login=async(username,password)=>{const {user:u}=await api('/auth/login',{method:'POST',body:JSON.stringify({username,password})});setUser(u);setPage(NAV[u.role][0][0]);await loadData();if(u.role!=='delivery')setAccounts((await api('/auth/users')).users)};
 const logout=async()=>{try{await api('/auth/logout',{method:'POST'})}finally{setUser(null);setData(null);setAccounts([]);setPage('dash')}};
 const {orders,stock,customers}=data||EMPTY_DATA,menu=(data||EMPTY_DATA).menu||{},role=user?.role;
 const cust=id=>customers.find(c=>c.id===id)||{id,name:'Deleted customer',phone:'',addr:'',dir:'—'};
 const live=orders.filter(o=>o.status!=='Cancelled');
 const balance=o=>Math.max(0,o.amount-paidOf(o));
 const due=id=>orders.filter(o=>o.c===id&&o.status!=='Cancelled').reduce((a,o)=>a+balance(o),0);
 const upd=(id,p)=>{if(role==='delivery'){api(`/business/orders/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(p)}).then(({order})=>setData(d=>({...d,orders:d.orders.map(o=>o.id===id?order:o)}))).catch(e=>setToast({t:'Order update failed',m:e.message}));return}update(d=>({...d,orders:d.orders.map(o=>o.id===id?{...o,...p}:o)}))};
 const voidInv=o=>{update(d=>{const usage=(d.stockMoves||[]).filter(m=>(m.type==='Order usage'||m.type==='Finished product sold')&&m.reason===o.id),restore=usage.length?Object.fromEntries(usage.map(m=>[m.name,-m.delta])):(o.lines||[{item:o.item,qty:o.qty}]).reduce((a,l)=>{Object.entries((d.menu||{})[l.item]?.r||{}).forEach(([n,q])=>a[n]=(a[n]||0)+q*l.qty);return a},{}),at=new Date().toISOString(),finishedRestore=Object.fromEntries(usage.filter(m=>m.type==='Finished product sold').map(m=>[m.name,-m.delta]));return {...d,stock:d.stock.map(s=>({...s,qty:s.qty+(restore[s.name]||0)})),finishedStock:Object.fromEntries(Object.keys(d.menu||{}).map(k=>[k,(d.finishedStock?.[k]||0)+(finishedRestore[k]||0)])),orders:d.orders.map(x=>x.id===o.id?{...x,status:'Cancelled'}:x),stockMoves:[...(d.stockMoves||[]),...Object.entries(restore).filter(([,q])=>q>0).map(([name,q])=>({id:crypto.randomUUID(),at,name,type:'Invoice cancellation reversal',delta:q,unit:d.stock.find(s=>s.name===name)?.u||'pcs',reason:o.id}))]}});setToast({t:o.id+' cancelled',m:'Recorded ingredient and finished-stock deductions were reversed.'})};
 const addOrder=(o,need)=>{update(d=>({...d,orders:[...d.orders,o],next:d.next+1,stock:d.stock.map(s=>({...s,qty:Math.max(0,s.qty-(need[s.name]||0))})),finishedStock:Object.fromEntries(Object.keys(d.menu||{}).map(k=>[k,Math.max(0,(d.finishedStock?.[k]||0)-(o.finishedUses?.[k]||0))])),stockMoves:[...(d.stockMoves||[]),...Object.entries(need).filter(([,q])=>q>0).map(([name,q])=>({id:crypto.randomUUID(),at:o.createdAt,name,type:'Order usage',delta:-Math.min(q,d.stock.find(s=>s.name===name)?.qty||0),unit:d.stock.find(s=>s.name===name)?.u||'pcs',reason:o.id})),...Object.entries(o.finishedUses||{}).filter(([,q])=>q>0).map(([name,q])=>({id:crypto.randomUUID(),at:o.createdAt,name,type:'Finished product sold',delta:-q,unit:'boxes',reason:o.id}))]}));setModal(false);setToast({t:o.id+' created',m:`Invoice total ${money(o.amount)} · balance due ${money(o.amount-paidOf(o))}`})};
 const recordPayment=(id,method,amount)=>{const n=Number(amount);const o=orders.find(x=>x.id===id);if(!o||!Number.isFinite(n)||n<=0||n>balance(o))return false;const entry={method,amount:n,at:new Date().toISOString()};upd(id,{payments:role==='delivery'?[entry]:[...(o.payments||[]),entry]});setPayment(null);setToast({t:'Payment recorded',m:`${money(n)} received by ${method} for ${id}.`});return true};
 const openWhatsApp=(phone,message)=>{const raw=String(phone||'').replace(/\D/g,''),number=/x/i.test(String(phone||''))?'':raw.startsWith('0')?'977'+raw.slice(1):raw.startsWith('977')?raw:raw?`977${raw}`:'';window.open(`https://wa.me/${number}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')};
 const assign=(o,d)=>{upd(o.id,{driver:d||null});if(d){const c=cust(o.c),message=`New Delivery Assigned\nCustomer: ${c.name} | Phone: ${c.phone}\nAddress: ${c.addr} | Direction: ${c.dir}\nOrder: ${(o.lines||[{item:o.item,qty:o.qty}]).map(l=>`${l.qty} x ${l.item}`).join(', ')} | Amount: ${money(o.amount)}\nPayment: ${balance(o)>0?'Collect '+money(balance(o)):'Paid'} | Note: ${o.note||'Call before arriving.'}`;openWhatsApp('',message);setToast({t:'Delivery assigned',m:`Order assigned to ${d}. WhatsApp opened so you can select the delivery person and send the details.`})}};
 const remind=c=>{const dueOrders=orders.filter(o=>o.c===c.id&&o.status!=='Cancelled'&&balance(o)>0),details=dueOrders.map(o=>`Invoice #${o.id}: ${money(balance(o))} due (${(o.lines||[{item:o.item,qty:o.qty}]).map(l=>`${l.qty} x ${l.item}`).join(', ')})`).join('\n'),message=`Dear ${c.name}, your payment is pending.\n${details}\nTotal outstanding: ${money(due(c.id))}\nPlease pay at your earliest convenience. Thank you - ${data.settings.businessName}.`;update(d=>({...d,reminders:[...(d.reminders||[]),{id:crypto.randomUUID(),customerId:c.id,at:new Date().toISOString(),invoiceIds:dueOrders.map(o=>o.id),amount:due(c.id)}]}));openWhatsApp(c.phone,message);setToast({t:'WhatsApp reminder ready',m:`A message for ${c.name} opened in WhatsApp. Send it there to complete delivery.`})};
 const addCustomer=c=>{update(d=>({...d,customers:[...d.customers,{...c,id:Math.max(0,...d.customers.map(x=>x.id))+1}]}));setToast({t:'Customer added',m:c.name+' is ready for billing.'})};
 const addStock=(name,qty,min)=>{const n=Number(qty),m=Number(min);if(!name.trim()||!Number.isFinite(n)||n<=0||!Number.isFinite(m)||m<0)return false;update(d=>{const found=d.stock.find(s=>s.name.toLowerCase()===name.trim().toLowerCase());return {...d,stock:found?d.stock.map(s=>s.name.toLowerCase()===name.trim().toLowerCase()?{...s,qty:s.qty+n,min:m}:s):[...d.stock,{name:name.trim(),qty:n,min:m,u:'pcs'}],stockMoves:[...(d.stockMoves||[]),{id:crypto.randomUUID(),at:new Date().toISOString(),name:name.trim(),type:'Stock in',delta:n,unit:found?.u||'pcs',reason:'Manual receipt'}]}});setReceive(null);return true};
 const moveStock=(name,type,qty,reason)=>{const n=Number(qty),item=stock.find(s=>s.name===name);if(!item||!Number.isFinite(n)||n<=0||!reason.trim())return false;const delta=type==='Adjustment'?n-item.qty:['Stock in','Customer return'].includes(type)?n:-n;if(item.qty+delta<0)return false;update(d=>({...d,stock:d.stock.map(s=>s.name===name?{...s,qty:s.qty+delta}:s),stockMoves:[...(d.stockMoves||[]),{id:crypto.randomUUID(),at:new Date().toISOString(),name,type,delta,unit:item.u,reason:reason.trim()}]}));return true};
 const addSupplier=s=>{const value={...s,id:crypto.randomUUID(),createdAt:new Date().toISOString()};update(d=>({...d,suppliers:[...(d.suppliers||[]),value]}));return value};
 const addPurchase=(supplierId,item,qty,unitCost)=>{const n=Number(qty),cost=Number(unitCost),material=stock.find(s=>s.name===item);if(!supplierId||!material||n<=0||cost<0)return false;const purchase={id:crypto.randomUUID(),supplierId,item,qty:n,unitCost:cost,at:new Date().toISOString()};update(d=>({...d,stock:d.stock.map(s=>{if(s.name!==item)return s;const total=s.qty+n;return {...s,qty:total,averageCost:total?((s.qty*(s.averageCost||0))+(n*cost))/total:0}}),purchases:[...(d.purchases||[]),purchase],stockMoves:[...(d.stockMoves||[]),{id:crypto.randomUUID(),at:purchase.at,name:item,type:'Purchase',delta:n,unit:material.u,reason:`Supplier purchase · ${purchase.id}`}]}));return true};
 const addExpense=e=>update(d=>({...d,expenses:[...(d.expenses||[]),{...e,id:crypto.randomUUID(),at:new Date().toISOString()}]}));
 const low=stock.filter(s=>s.qty<s.min),sales=live.reduce((a,o)=>a+o.amount,0),outstanding=customers.reduce((a,c)=>a+due(c.id),0),vatRate=Math.max(0,Number(data?.settings?.vatRate)||13);
 const invoice=o=><InvoiceDocument order={o} business={data.settings} customer={cust(o.c)} balance={balance(o)} paid={paidOf(o)} method={methodOf(o)} money={money} date={nepalDate} menu={menu}/>;
 const orderRows=rows=><>{rows.map(o=><tr key={o.id}><td className="font-semibold">{o.id}</td><td>{cust(o.c).name}</td><td>{(o.lines||[{item:o.item,qty:o.qty}]).map(l=>`${l.qty} × ${l.item}`).join(', ')}</td><td>{money(o.amount)}</td><td>{money(balance(o))}</td><td><Badge c={SC[o.status]}>{o.status}</Badge></td><td><Badge c={balance(o)===0?'bg-leaf/15 text-leaf':paidOf(o)>0?'bg-accent/15 text-orange-700':'bg-brand/10 text-brand'}>{balance(o)===0?'Paid':paidOf(o)>0?'Partial':'Unpaid'} · {methodOf(o)}</Badge></td></tr>)}</>;
 const filtered=orders.filter(o=>(o.id+' '+cust(o.c).name+' '+cust(o.c).phone).toLowerCase().includes(search.toLowerCase()));
 const filteredOrders=filtered.filter(o=>statusFilter==='All'||o.status===statusFilter).map(o=>({...o,customer:cust(o.c).name,items:(o.lines||[{item:o.item,qty:o.qty}]).map(l=>`${l.qty} x ${l.item}`).join('; ')}));
 if(!authReady)return <div className="min-h-screen grid place-items-center text-stone-600">Checking sign-in…</div>;
 if(!user)return <Login onLogin={login}/>;
 if(!data)return <div className="min-h-screen grid place-items-center text-stone-600">Loading business data…</div>;
 const pages={
  dash:<><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Stat l="Active orders" v={live.length} c="#E62227"/><Stat l="Sales · all time" v={money(sales)} c="#057947"/><Stat l="Outstanding" v={money(outstanding)} c="#F58220"/><Stat l="Low stock" v={low.length} c="#2B3F8C"/></div><div className="grid lg:grid-cols-3 gap-4 mt-4"><Card title="Recent invoices" cls="lg:col-span-2"><Table head={['Invoice','Customer','Items','Total','Balance','Status','Payment']}>{orderRows(orders.slice(-6).reverse())}</Table></Card><Card title="Low stock alerts">{low.length?low.map(s=><div key={s.name} className="flex justify-between py-2 border-b border-cream-200"><span>{s.name}</span><Badge c="bg-brand/10 text-brand">{fmt(s)} left</Badge></div>):<p className="text-stone-500">All ingredients are above minimum level.</p>}</Card></div></>,
  orders:<Card title="Orders & bills" right={<div className="flex gap-2"><Btn c="bg-navy text-white" onClick={()=>downloadCsv('orders',filteredOrders,[['Invoice','id'],['Customer','customer'],['Ordered at','createdAt'],['Items','items'],['Quantity','qty'],['Total','amount'],['Status','status']])}>Export data</Btn><Btn onClick={()=>setModal(true)}>New customer bill</Btn></div>}><Table head={['Invoice','Customer','Items','Total','Balance','Status','Payment','Update']}>{filteredOrders.map(o=><tr key={o.id}><td className="font-semibold">{o.id}</td><td>{cust(o.c).name}</td><td>{(o.lines||[{item:o.item,qty:o.qty}]).map(l=>`${l.qty} × ${l.item}`).join(', ')}</td><td>{money(o.amount)}</td><td>{money(balance(o))}</td><td><Badge c={SC[o.status]}>{o.status}</Badge></td><td><Badge c="bg-cream-200 text-stone-700">{methodOf(o)}</Badge></td><td><select aria-label="Update order status" value={o.status} onChange={e=>upd(o.id,{status:e.target.value})} className="border border-cream-300 bg-white rounded-lg px-2 py-1">{STAT.map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</Table></Card>,
  bill:<Card title="Customer invoices" right={<Btn onClick={()=>setModal(true)}>Create invoice</Btn>}><div className="flex flex-wrap gap-3 mb-4"><input className="flex-1 min-w-48 rounded-lg border border-cream-300 px-3 py-2" placeholder="Search customer or invoice" value={search} onChange={e=>setSearch(e.target.value)}/><span className="self-center text-sm text-stone-500">{filtered.length} invoices</span></div><Table head={['Invoice','Customer','Items','Total','Balance','Status','Payment','Actions']}>{filtered.map(o=><tr key={o.id}><td className="font-semibold">{o.id}</td><td>{cust(o.c).name}</td><td>{(o.lines||[{item:o.item,qty:o.qty}]).map(l=>`${l.qty} × ${l.item}`).join(', ')}</td><td>{money(o.amount)}</td><td className="font-semibold">{money(balance(o))}</td><td><Badge c={SC[o.status]}>{o.status}</Badge></td><td><div>{methodOf(o)}</div><small className="text-stone-500">Received {money(paidOf(o))}</small></td><td><div className="flex flex-wrap gap-1.5"><Btn c="bg-navy text-white" onClick={()=>setReceipt(o)}>View / print</Btn>{balance(o)>0&&<Btn c="bg-leaf text-white" onClick={()=>setPayment(o)}>Add payment</Btn>}{o.status!=='Cancelled'&&role==='admin'&&<Btn c="bg-white border border-brand text-brand" onClick={()=>voidInv(o)}>Cancel</Btn>}</div></td></tr>)}</Table></Card>,
  inv:<><Card title="Ingredient inventory" right={<div className="flex gap-2"><Btn c="bg-navy text-white" onClick={()=>downloadCsv('inventory',stock,[['Ingredient','name'],['Available quantity','qty'],['Unit','u'],['Minimum','min'],['Average cost','averageCost']])}>Export data</Btn><Btn onClick={()=>setReceive({name:'',qty:'',min:''})}>Receive stock</Btn></div>}><Table head={['Ingredient','Available','Minimum','Stock level','Action']}>{stock.map(s=>{const pct=Math.min(100,s.qty/Math.max(s.min*3,1)*100);return <tr key={s.name}><td className="font-semibold">{s.name}</td><td>{fmt(s)}</td><td>{fmt({...s,qty:s.min})}</td><td className="w-48"><div className="h-2.5 bg-cream-200 rounded-full"><div className={'h-full rounded-full '+(s.qty<s.min?'bg-brand':'bg-leaf')} style={{width:pct+'%'}}/></div><small>{s.qty<s.min?'Reorder needed':'In stock'}</small></td><td><Btn c="bg-white border border-cream-300" onClick={()=>setReceive({name:s.name,qty:'',min:String(s.min)})}>Add quantity</Btn></td></tr>})}</Table></Card><Card title="Finished product stock" cls="mt-4"><p className="text-sm text-stone-500">New orders use available prepared boxes when recorded; production is managed outside this reception and admin dashboard.</p>{Object.keys(menu).length?<div className="grid sm:grid-cols-3 gap-3 mt-3">{Object.entries(menu).map(([k,v])=><div key={k} className="rounded-xl bg-white border border-cream-300 p-3"><div className="text-stone-500 text-sm">{k}</div><div className="text-xl font-bold">{data.finishedStock?.[k]||0} ready · {money(v.price)} / box</div></div>)}</div>:<p className="mt-3 text-stone-500">No menu items yet. Add them under Business settings.</p>}</Card></>,
  del:<Card title="Delivery by direction" right={<div className="flex gap-1.5 flex-wrap">{['All','North','South','East','West'].map(d=><button key={d} onClick={()=>setDir(d)} className={'px-3 py-1 rounded-full text-sm font-semibold '+(dir===d?'bg-brand text-white':'bg-white border border-cream-300')}>{d}</button>)}</div>}><Table head={['Invoice','Customer','Direction','Address','Balance','Assign to']}>{live.filter(o=>o.status!=='Delivered'&&(dir==='All'||cust(o.c).dir===dir)).map(o=><tr key={o.id}><td className="font-semibold">{o.id}</td><td>{cust(o.c).name}</td><td>{cust(o.c).dir}</td><td>{cust(o.c).addr}</td><td>{money(balance(o))}</td><td><select aria-label="Assign delivery" value={o.driver||''} onChange={e=>assign(o,e.target.value)} className="border border-cream-300 bg-white rounded-lg px-2 py-1"><option value="">Unassigned</option>{accounts.filter(a=>a.role==='delivery'&&a.active).map(a=><option key={a.id}>{a.name}</option>)}</select></td></tr>)}</Table></Card>,
  cust:<><Card title="Customers & balances" right={<div className="flex gap-2"><Btn c="bg-navy text-white" onClick={()=>downloadCsv('customers',customers,[['Name','name'],['Phone','phone'],['Address','addr'],['Direction','dir']])}>Export data</Btn><Btn onClick={()=>setReceive({customer:true})}>Add customer</Btn></div>}><Table head={['Customer','Phone','Address','Direction','Outstanding','Actions']}>{customers.map(c=><tr key={c.id}><td className="font-semibold">{c.name}</td><td>{c.phone}</td><td>{c.addr}</td><td>{c.dir}</td><td>{due(c.id)?<Badge c="bg-brand/10 text-brand">{money(due(c.id))}</Badge>:<Badge c="bg-leaf/15 text-leaf">Clear</Badge>}</td><td><div className="flex gap-2">{due(c.id)>0&&<Btn c="bg-leaf text-white" onClick={()=>remind(c)}>Payment reminder</Btn>}<Btn c="bg-white border border-cream-300" onClick={()=>{setSearch(c.name);setPage('bill')}}>Invoices</Btn></div></td></tr>)}</Table></Card><Card title="Customer invoice ledger" cls="mt-4"><Table head={['Invoice','Customer','Total','Received','Balance','Payment']}>{orders.filter(o=>o.status!=='Cancelled'&&(!search||cust(o.c).name.toLowerCase().includes(search.toLowerCase()))).map(o=><tr key={o.id}><td><button className="text-navy underline" onClick={()=>setReceipt(o)}>{o.id}</button></td><td>{cust(o.c).name}</td><td>{money(o.amount)}</td><td>{money(paidOf(o))}</td><td>{money(balance(o))}</td><td>{methodOf(o)}</td></tr>)}</Table></Card></>,
  rep:<div className="grid md:grid-cols-2 gap-4"><Card title="Sales & payments summary"><div className="space-y-3 text-sm">{['Cash','QR'].map(m=><div key={m} className="flex justify-between border-b pb-2"><span>{m} received</span><b>{money(orders.flatMap(o=>o.payments||[]).filter(p=>p.method===m).reduce((a,p)=>a+p.amount,0))}</b></div>)}<div className="flex justify-between border-b pb-2"><span>Total invoiced</span><b>{money(sales)}</b></div><div className="flex justify-between"><span>Outstanding</span><b>{money(outstanding)}</b></div></div></Card><Card title="Orders by direction">{['North','South','East','West'].map(d=>{const n=live.filter(o=>cust(o.c).dir===d).length;return <div key={d} className="mb-3"><div className="flex justify-between text-sm"><span>{d}</span><b>{n}</b></div><div className="h-2.5 bg-cream-200 rounded-full"><div className="h-full rounded-full bg-leaf" style={{width:Math.min(100,n/Math.max(1,live.length)*100)+'%'}}/></div></div>})}</Card></div>,
  settings:<><Card title="Business and tax details"><form className="grid sm:grid-cols-2 gap-3" onSubmit={e=>e.preventDefault()}>{[['businessName','Business name'],['address','Business address'],['phone','Business phone'],['pan','Business PAN'],['vatNumber','VAT registration number']].map(([k,label])=><label key={k} className="text-sm">{label}<input className="w-full border border-cream-300 bg-white rounded-lg px-3 py-2 mt-1" value={data.settings[k]||''} onChange={e=>update(d=>({...d,settings:{...d.settings,[k]:e.target.value}}))}/></label>)}<label className="text-sm flex items-center gap-2 sm:col-span-2"><input type="checkbox" checked={!!data.settings.vatEnabled} onChange={e=>update(d=>({...d,settings:{...d.settings,vatEnabled:e.target.checked}}))}/>Add VAT to new invoices</label>{data.settings.vatEnabled&&<label className="text-sm">VAT rate (%)<input type="number" min="0" max="100" step="0.01" className="w-full border border-cream-300 bg-white rounded-lg px-3 py-2 mt-1" value={data.settings.vatRate} onChange={e=>update(d=>({...d,settings:{...d.settings,vatRate:Number(e.target.value)}}))}/></label>}</form><p className="mt-4 p-3 rounded-lg bg-cream-100 text-sm">VAT is optional and off by default. Nepal’s standard rate is 13%; set tax details to match your registration and ask your accountant to verify your invoices. The app does not connect to IRD or CBMS or provide statutory e-billing.</p></Card><Card title="Nepal locale and data backup" cls="mt-4"><p className="text-sm mb-3">Currency is Nepalese rupees. Invoice timestamps use Nepal time and Nepali date formatting.</p><div className="flex flex-wrap gap-2"><Btn onClick={()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`hamro-lunch-box-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}}>Download backup</Btn><label className="inline-flex items-center px-3.5 py-2 rounded-lg text-sm font-semibold bg-white border border-cream-300 cursor-pointer">Restore backup<input type="file" accept="application/json,.json" className="hidden" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const x=JSON.parse(await file.text());if(!Array.isArray(x.orders)||!Array.isArray(x.stock)||!Array.isArray(x.customers))throw new Error('Invalid backup');update(()=>({...x,settings:{...DEFAULT_SETTINGS,...(x.settings||{})}}));setToast({t:'Backup restored',m:'Your business records were loaded from the selected file.'})}catch{setToast({t:'Backup not restored',m:'This file is not a valid Hamro Lunch Box backup.'})}e.target.value=''}}/></label></div></Card></>,
  mine:<div className="grid md:grid-cols-2 gap-4">{orders.filter(o=>o.driver===user.name&&o.status!=='Cancelled').map(o=><Card key={o.id} title={cust(o.c).name} right={<Badge c={SC[o.status]}>{o.status}</Badge>}><div className="text-sm space-y-1"><p>{cust(o.c).addr} · <b>{cust(o.c).dir}</b></p><p>Phone: {cust(o.c).phone}</p>{o.note&&<p><b>Delivery note:</b> {o.note}</p>}<p>{o.id} · {(o.lines||[{item:o.item,qty:o.qty}]).map(l=>`${l.qty} × ${l.item}`).join(', ')}</p><p className="text-lg font-bold">{balance(o)===0?'Paid':`Collect ${money(balance(o))}`}</p></div><div className="flex gap-2 mt-3"><Btn c="bg-navy text-white" onClick={()=>upd(o.id,{status:'Out for Delivery'})}>Start delivery</Btn>{balance(o)>0&&<Btn c="bg-accent text-white" onClick={()=>setPayment(o)}>Record collection</Btn>}<Btn c="bg-leaf text-white" onClick={()=>upd(o.id,{status:'Delivered'})}>Mark delivered</Btn></div></Card>)}</div>
 };
 pages.move=<StockControl stock={stock} moves={data.stockMoves||[]} onMove={moveStock}/>;
 pages.cust=<>{pages.cust}<CustomerOrderHistory customers={customers} orders={orders}/></>;
 pages.favorites=<CustomerFavorites customers={customers} orders={orders}/>;
 pages.settings=<>{pages.settings}<MenuEditor menu={menu} stock={stock} onSave={next=>update(d=>({...d,menu:next}))}/></>;
 
 pages.sup=<SupplierPurchases stock={stock} suppliers={data.suppliers||[]} purchases={data.purchases||[]} onSupplier={addSupplier} onPurchase={addPurchase}/>;
 pages.exp=<Expenses expenses={data.expenses||[]} onAdd={addExpense}/>;
 pages.rep=<Reports orders={orders} expenses={data.expenses||[]} purchases={data.purchases||[]} moves={data.stockMoves||[]}/>;
 pages.rem=<ReminderHistory reminders={data.reminders||[]} customers={customers} orders={orders}/>;
 pages.staff=<StaffDetails staff={data.staff||[]} onSave={s=>update(d=>({...d,staff:[...(d.staff||[]),s]}))} onDelete={id=>update(d=>({...d,staff:d.staff.filter(s=>s.id!==id)}))}/>;
 pages.accounts=<UserAccounts accounts={accounts} onChange={setAccounts}/>;
 return <div className="min-h-screen md:flex"><aside className="md:flex md:flex-col md:overflow-hidden md:w-60 md:min-h-0 bg-cream-50 border-b md:border-r border-cream-300 p-3 md:p-4 md:sticky md:top-0 md:h-screen"><div className="flex md:block items-center gap-3"><img src={LOGO} alt="Hamro Lunch Box" className="w-16 md:w-40 md:mx-auto rounded-lg bg-white"/><div className="md:text-center md:mt-2 text-sm"><div className="font-bold text-brand">Hamro Lunch Box</div><div className="text-stone-500">{user.name}<span className="capitalize"> · {role}</span></div></div></div><nav className="flex min-w-0 max-w-full md:min-h-0 md:flex-1 md:flex-col gap-1.5 mt-3 overflow-x-auto overflow-y-hidden md:overflow-x-hidden md:overflow-y-auto">{NAV[role].map(([k,l])=><button key={k} onClick={()=>setPage(k)} className={'text-left shrink-0 md:shrink md:whitespace-normal md:w-full px-3 py-2 rounded-lg font-semibold text-sm break-words '+(page===k?'bg-brand text-white':'hover:bg-cream-200 text-stone-700')}>{l}</button>)}<button onClick={logout} className="shrink-0 md:shrink md:whitespace-normal md:w-full px-3 py-2 rounded-lg text-sm text-leaf font-semibold md:mt-4 text-left">Sign out</button></nav></aside><main className="flex-1 p-4 md:p-6 min-w-0"><h1 className="text-2xl font-bold mb-4 text-stone-800">{(NAV[role].find(n=>n[0]===page)||[])[1]}</h1>{NAV[role].some(n=>n[0]===page)&&pages[page]}</main>
 {modal&&<NewOrder stock={stock} customers={customers} productStock={data.finishedStock||{}} settings={data.settings} menu={menu} canOverride={role==='admin'} close={()=>setModal(false)} add={addOrder} next={`INV-${String(data.next||1).padStart(4,'0')}`}/>}
 {receipt&&<div className="invoice-overlay fixed inset-0 bg-black/40 z-20 overflow-y-auto p-4"><div className="max-w-3xl mx-auto"><div className="flex justify-end gap-2 mb-2 noprint"><Btn c="bg-white" onClick={()=>setReceipt(null)}>Close</Btn><Btn c="bg-navy text-white" onClick={()=>window.print()}>Print invoice</Btn></div>{invoice(receipt)}</div></div>}
 {payment&&<PaymentModal order={payment} due={balance(payment)} close={()=>setPayment(null)} save={recordPayment}/>}
 {receive&&<DataModal initial={receive} stock={stock} close={()=>setReceive(null)} addStock={addStock} addCustomer={addCustomer}/>}
 {toast&&<div role="status" className="fixed bottom-4 right-4 left-4 sm:left-auto sm:w-96 bg-white border-l-4 border-leaf rounded-xl shadow-lg p-4 noprint z-30"><div className="flex justify-between"><b>{toast.t}</b><button onClick={()=>setToast(null)} aria-label="Close" className="text-stone-400">×</button></div><pre className="text-sm whitespace-pre-wrap font-sans text-stone-600 mt-1">{toast.m}</pre></div>}
 </div>;
}
function PaymentModal({order,due,close,save}){const [method,setMethod]=useState('Cash'),[amount,setAmount]=useState(due),[err,setErr]=useState('');const submit=e=>{e.preventDefault();if(!save(order.id,method,amount))setErr('Enter an amount greater than zero and no more than the remaining balance.')};return <div className="fixed inset-0 z-30 bg-black/40 grid place-items-center p-4"><form onSubmit={submit} className="bg-cream-50 rounded-2xl p-5 w-full max-w-sm grid gap-3"><h2 className="font-bold text-lg">Record payment · {order.id}</h2><p className="text-sm">Remaining balance: <b>{money(due)}</b></p><label className="text-sm">Payment method<select className="w-full border border-cream-300 rounded-lg p-2 bg-white" value={method} onChange={e=>setMethod(e.target.value)}>{['Cash','QR','eSewa','Khalti','Fonepay','Bank transfer','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm">Amount (रु.)<input type="number" min="0.01" max={due} step="0.01" className="w-full border border-cream-300 rounded-lg p-2 bg-white" value={amount} onChange={e=>setAmount(e.target.value)} required/></label>{err&&<p role="alert" className="text-brand text-sm">{err}</p>}<div className="flex justify-end gap-2"><Btn type="button" c="bg-white border border-cream-300" onClick={close}>Cancel</Btn><Btn type="submit">Save payment</Btn></div></form></div>}
function DataModal({initial,stock,close,addStock,addCustomer}){const [customer,setCustomer]=useState(!!initial.customer),[name,setName]=useState(initial.name||''),[qty,setQty]=useState(''),[min,setMin]=useState(initial.min||'0'),[phone,setPhone]=useState(''),[addr,setAddr]=useState(''),[dir,setDir]=useState('East'),[err,setErr]=useState('');const field='w-full border border-cream-300 rounded-lg p-2 bg-white';const submit=e=>{e.preventDefault();if(customer){const digits=phone.replace(/[\s-]/g,'').replace(/^\+977/,'');if(!name.trim()||!addr.trim()||!/^9[678]\d{8}$/.test(digits))return setErr('Enter a name, address and valid 10-digit Nepal mobile number.');addCustomer({name:name.trim(),phone:phone.trim(),addr:addr.trim(),dir});close()}else{if(!addStock(name,qty,min))setErr('Enter an item name and a positive quantity, with a valid minimum level.')}};return <div className="fixed inset-0 z-30 bg-black/40 grid place-items-center p-4"><form onSubmit={submit} className="bg-cream-50 rounded-2xl p-5 w-full max-w-sm grid gap-3"><h2 className="font-bold text-lg">{customer?'Add customer':'Receive inventory'}</h2>{customer?<><label className="text-sm">Full name<input className={field} value={name} onChange={e=>setName(e.target.value)}/></label><label className="text-sm">Nepal mobile number<input type="tel" inputMode="tel" placeholder="98XXXXXXXX or +977 98XXXXXXXX" className={field} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="text-sm">Address<input className={field} value={addr} onChange={e=>setAddr(e.target.value)}/></label><label className="text-sm">Direction<select className={field} value={dir} onChange={e=>setDir(e.target.value)}>{['North','South','East','West'].map(x=><option key={x}>{x}</option>)}</select></label></>:<><label className="text-sm">Ingredient / item<select className={field} value={name} onChange={e=>setName(e.target.value)}><option value="">Choose existing or type new…</option>{stock.map(s=><option key={s.name}>{s.name}</option>)}</select><input className={field+' mt-2'} aria-label="New ingredient name" placeholder="Or enter a new ingredient" value={stock.some(s=>s.name===name)?'':name} onChange={e=>setName(e.target.value)}/></label><label className="text-sm">Quantity to receive<input type="number" min="0.01" step="any" className={field} value={qty} onChange={e=>setQty(e.target.value)} required/></label><label className="text-sm">Minimum stock alert<input type="number" min="0" step="any" className={field} value={min} onChange={e=>setMin(e.target.value)} required/></label></>}{err&&<p role="alert" className="text-brand text-sm">{err}</p>}<div className="flex justify-end gap-2"><Btn type="button" c="bg-white border border-cream-300" onClick={close}>Cancel</Btn><Btn type="submit">{customer?'Save customer':'Receive stock'}</Btn></div></form></div>}
