export const P={'Chicken Lunch Box':{price:250,r:{Rice:250,Chicken:150,Vegetables:100,Oil:20,Packaging:1}},'Veg Lunch Box':{price:200,r:{Rice:250,Vegetables:200,Oil:20,Packaging:1}},'Special Lunch Box':{price:350,r:{Rice:300,Chicken:200,Vegetables:150,Oil:30,Packaging:1}}};
export const S0=[{name:'Rice',qty:40000,min:10000,u:'g'},{name:'Chicken',qty:4200,min:5000,u:'g'},{name:'Vegetables',qty:18000,min:5000,u:'g'},{name:'Oil',qty:3500,min:1000,u:'ml'},{name:'Packaging',qty:260,min:100,u:'pcs'}];
export const C0=[{id:1,name:'Ram Sharma',phone:'98XXXXXXXX',addr:'Milan Chowk, Bhairahawa',dir:'East'},{id:2,name:'Sita Thapa',phone:'98XXXXXXX1',addr:'Buddha Chowk',dir:'West'},{id:3,name:'Hari Gurung',phone:'98XXXXXXX2',addr:'Traffic Chowk',dir:'North'},{id:4,name:'Maya Karki',phone:'98XXXXXXX3',addr:'Tilottama Road',dir:'South'},{id:5,name:'Bikash Rana',phone:'98XXXXXXX4',addr:'Lumbini Road',dir:'East'}];
export const O0=[['INV-0120',1,'Chicken Lunch Box',2,'Delivered','Paid',null],['INV-0121',2,'Veg Lunch Box',3,'Out for Delivery','Unpaid','Delivery Person A'],['INV-0122',3,'Special Lunch Box',1,'Preparing','Credit',null],['INV-0123',1,'Chicken Lunch Box',2,'Ready','Unpaid','Delivery Person A'],['INV-0124',4,'Veg Lunch Box',4,'Pending','Paid',null],['INV-0125',5,'Chicken Lunch Box',5,'Pending','Credit',null]].map(([id,c,item,qty,status,pay,driver])=>({id,c,item,qty,status,pay,driver,amount:P[item].price*qty}));
export const STAT=['Pending','Preparing','Ready','Out for Delivery','Delivered','Cancelled'];
export const SC={Pending:'bg-accent/15 text-orange-700',Preparing:'bg-navy/10 text-navy','Ready':'bg-leaf/10 text-leaf','Out for Delivery':'bg-navy/10 text-navy',Delivered:'bg-leaf/15 text-leaf',Cancelled:'bg-stone-200 text-stone-600'};
export const PC={Paid:'bg-leaf/15 text-leaf',Unpaid:'bg-brand/10 text-brand',Credit:'bg-accent/15 text-orange-700'};
export const fmt=s=>s.u==='g'?(s.qty/1000).toFixed(1)+' kg':s.u==='ml'?(s.qty/1000).toFixed(1)+' L':s.qty+' pcs';
export const NAV={admin:[['dash','Dashboard'],['orders','Orders'],['bill','Billing & invoices'],['inv','Inventory'],['production','Kitchen production'],['move','Stock movements'],['rec','Recipes'],['sup','Suppliers & purchases'],['exp','Expenses'],['del','Delivery'],['cust','Customers'],['rem','Reminder history'],['rep','Reports'],['staff','Staff access'],['settings','Business settings']],reception:[['dash','Dashboard'],['orders','Orders'],['bill','Billing & invoices'],['del','Delivery'],['cust','Customers'],['rem','Reminder history']],delivery:[['mine','My deliveries']]};

export const USERS=[{username:'admin',password:'admin123',role:'admin',name:'Admin'},{username:'reception',password:'reception123',role:'reception',name:'Receptionist'},{username:'driver1',password:'driver123',role:'delivery',name:'Delivery Person A'},{username:'driver2',password:'driver123',role:'delivery',name:'Delivery Person B'}];
